[program:gestion-cv-redis-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/gestion-cv/artisan queue:work redis --sleep=3 --tries=3 --timeout=0
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=3600
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gestion-cv-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
user=www-data
environment=APP_ENV=production,APP_DEBUG=false

[group:gestion-cv-workers]
programs=gestion-cv-redis-worker
priority=999
